lib/api_callable.js, package.json, test/api_callable.js
grpc 0.13.1 -- request, callback, metadata, options
grpc 0.14.1 -- request, metadata, options, callback
It's better to follow the latest version.
=> Modify again for API call argument order.

package.json
=> Update eventemitter2 dependency to 2.0.2

package.json
package.json.[files[]](https://docs.npmjs.com/files/package.json#files) is a whitelist of files that are included when a user `npm install`s the module. In the case of this repo, we can get rid of the various config files (`.gitignore`, `.eslintrc.yml`, etc), build scripts, and tests.
All that's required to specify is `lib`. `index.js`, `LICENSE`, and `README.md` are included automatically.
=> Add files array to package.json

lib/operations_api.js
The require statement is slightly wrong, because it's a part
of gax library.
=> Fix sample code manually for operations_api.

lib/api_callable.js, package.json, test/api_callable.js
=> Remove 'cause' pattern for errors.

lib/api_callable.js, lib/gax.js, test/api_callable.js
Fixes https://github.com/googleapis/gax-nodejs/issues/38
cc @bjwatson
=> Max retries implementation

package.json
The newer version includes gRPC-streaming support.
=> Updating the package version to 0.9.0

lib/api_callable.js, lib/gax.js, lib/operations_api.js, lib/page_streaming.js, package.json, test/api_callable.js
=> Refine page streaming

package.json
This includes the refinement of page streaming
=> Update gax-nodejs version to 0.10.0

lib/bundling.js, lib/grpc.js, lib/longrunning.js, lib/page_streaming.js, lib/streaming.js, test/api_callable.js
=> Removed uses of `.bind`.

index.js, lib/longrunning.js, test/api_callable.js
=> Expose method to create operation.

lib/longrunning.js, test/api_callable.js
=> Introduce metadata and result fields to gax.operations

lib/bundling.js, test/bundling.js
=> Fix erroneous behaviors of missing discriminator fields on bundling.

lib/gax.js, lib/paged_iteration.js, package.json, test/paged_iteration.js
- Fix #123: introduces maxResults parameter
- Fix #124: fixed the behaviors of the streaming
it seems better to be back of using through2.
=> Fixes for paged iterations.

package.json
- grpc version minimum to 1.2
- fixes on paged iterations
=> Update gax-nodejs version

lib/grpc.js, package.json, test/fixtures/google/example/library/v1/missing_include.proto, test/grpc.js
=> Fix issue loading proto files on windows.

.travis.yml
=> Test on Node 8.

lib/api_callable.js, package.json
Hopefully the last manual release. New continuous integration experience expected after this one!
=> release 0.14.3

package.json
=> chore: releasing 0.14.4

package.json
=> fix(package): update grpc to version 1.9.1

package.json
Draft release notes:
---
This release has several dependencies updates, most importantly, `grpc` is upgraded to version 1.9.1.
=> Releasing v0.15.0

.gitignore, package-lock.json
This repository is always forgotten when we make big changes.
=> chore: adding package-lock.json

package-lock.json
🔨 update lock files to use the latest gRPC
=> chore: lock files maintenance

test/bundling.ts
=> fix: un-flake timer test

README.md, package.json
=> docs: improve the readme

src/index.ts, src/operations_client.ts
=> fix: enable new gax.lro()

package.json
[release notes](https://github.com/googleapis/gax-nodejs/releases/edit/untagged-01f909b394048c87cd88)
=> chore: release 0.17.1

package.json
=> Add missing semver dependency

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.21.0

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.22.0

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.23.0

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.24.0

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.25.0

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.25.1

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.25.2

src/index.ts
=> chore(typescript): export common API call types

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.25.3

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.25.4

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.25.5

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.25.6

package.json, system-test/system.ts
PANIC PANIC IT DOES NOT WORK 😱
=> pin grpc 1.20.0

system-test/test.clientlibs.ts
Looks like extensive use of `npm link` was triggering that `semver` bug. Let's not use `npm link` in system tests, using `npm pack` and depending on a tarball instead. It just works.
=> test: use npm pack instead of npm link

CHANGELOG.md, package.json, samples/package.json
=> Release google-gax v0.26.0

README.md
=> docs: mark lib as GA

src/browser.ts
=> remove foo

src/browser.ts
Decided to use serviceStub where LangaugeServiceStub was used
=> Renamed references to LangaugeService

src/browser.ts, src/grpc.ts, src/operationsClient.ts, src/operationsClientBrowser.ts
First pass of trying to add documentation, any critiques or missing areas are appreciated.
=> Adding JSDoc Documentation

src/index.ts
Adding some exports for TypeScript clients.
=> feat: export CancellableStream

test/unit/longrunning.ts
This added test covers the situation described in https://github.com/googleapis/nodejs-dialogflow/issues/450 (and turns out it actually works as expected).
=> test: what if LRO completes immediately

src/index.ts
=> feat: export GaxCall in apiTypes

test/unit/compileProtos.ts, tools/compileProtos.ts
Making the license bot completely happy.
=> fix: add license to protos/protos.js

src/normalCalls/retries.ts
=> fix: fix possible invalid retry variables

src/index.ts
For supporting bundle requests in micro-generator: https://github.com/googleapis/gapic-generator-typescript/pull/330
=> feat: export bundle descriptor in descriptors interface

package.json, src/operationsClient.ts, tsconfig.json
=> build: use TypeScript ^3.8.3, set lib to es2018

package.json, samples/package.json, samples/system-test/test.pagination.js, samples/system-test/test.quickstart.js, test/browser-test/test.endtoend.ts, test/browser-test/test.grpc-fallback.ts, test/unit/apiCallable.ts, test/unit/bundling.ts, test/unit/gax.ts, test/unit/grpc-fallback.ts, test/unit/grpc.ts, test/unit/longrunning.ts, test/unit/pagedIteration.ts, test/unit/pathTemplate.ts, test/unit/pathTemplateParser.ts, test/unit/routingHeader.ts, test/unit/streaming.ts, test/unit/utils.ts, test/unit/warning.ts
something.had.to.be.done.about(this.testing.style)
=> test: use built in assert
