.travis.yml, package.json
0.12.0 is the least version which gcloud-node supports, we want to
keep this as far as possible.
=> Explicitly specify node version requirement

lib/auth.js, lib/grpc.js, test/auth.js
I've noticed that Promise fits well to the holder pattern we've
introduced for auth and credentials. This reduces the code
significantly, and Promise would be beneficial thanks to
its composability (and because it's a language feature).
=> Use Promise for holding values

jsdoc.conf, lib/api_callable.js, lib/auth.js, lib/gax.js, lib/grpc.js, lib/parser_extras.js, lib/path_template.js, package.json
This adds jsdoc generation rules to package.json, and made a few fixes on comment styles.
Also attached the result of the doc htmls.
=> Add jsdoc generation rules

lib/api_callable.js, test/api_callable.js
Currently createApiCall assumes to receive a function and
a CallSettings instance, and then returns a function.
On the reality, however, the API function can't be a normal
function but a Promise to a function (due to the asynchronous-ness
of auth library) and therefore, it's hard to handle the return
value of the code upon usage.
With this refactoring, the generated code can simply invokes
createApiCall with a Promise stub, and it simplifies the return
values.
This is a preparation to #20, which requires a different type of
return value to non-page-streaming functions, and #22 which will
also return a value.
This also reduces the size of the generated code because the
pattern used in the API call can be simplified. See
https://github.com/jmuk/toolkit/commit/ec23b2508a9e32350c803fcdf003acb5 …
=> Refactor createApiCall

index.js, lib/api_callable.js, package.json, test/api_callable.js
Fixes #20 and #21.
This introduces a dependency on eventemitter2 instead of using
NodeJS default EventEmitter considering the portability with
browserJS environment.
=> Introduce event emitter.

index.js, lib/grpc.js, package.json
- BundleDescriptor must be exposed (it's used by Gapic generated code)
- encoder() is wrong, encode() is correct.
- update to gRPC-0.15.0
=> Minor fixes

.travis.yml
- Add v6 -- which is going to be active LTS version soon.
- Remove unnecessary versions. Simply keep tracking the latest
versions of each of LTS.
- Although gcloud-node does not verify v5 -- and it's not going
to be LTS, it's probably good to check v5 behavior for now.
We can remove it when Node switches to v6 as the new LTS.
cf: https://github.com/nodejs/LTS and
https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/.travis.yml
=> Fix testing nodejs versions in Travis.

index.js
For googleapis/toolkit#467, we'll have to reveal the version of gax.
=> Allow accessing gax version.

lib/gax.js, test/gax.js
Also, the default value for timeout in CallSettings is actually
wrong -- just '30' means 30 milliseconds.
=> Add the support of 'timeout_millis' field.

lib/grpc.js, package.json
This is wanted for idiomatic nodejs clients -- all of the internal
fields will be lowercased_underscore style.
Fixes #43, and #41.
=> Specify convertFieldsToCamelCase to true by default

lib/bundling.js, lib/gax.js, test/api_callable.js, test/bundling.js
This happens due to support of grpc streaming -- function should
return an object with cancel method.
=> Fix the return value of bundling.

lib/streaming.js, package.json, test/api_callable.js
- 'metadata' and 'status' events are meaningful and should be
forwarded.
- gRPC streaming results have 'cancel' method, this method call
needs to be forwarded as well.
Fixes #67
=> Support more gRPC streaming events.

lib/api_callable.js, lib/page_streaming.js, package.json, test/api_callable.js
fixes #74. This also includes the fix for #69, to detach the
callback from unhandled promises.
=> Let apiCallable return undefined when callback is supplied.

lib/longrunning.js, package.json, test/api_callable.js
Comparing `Buffer` objects using the `!==` operator always returns `true`. Switching this comparison to use `Buffer.compare` will cause the `progress` event to work correctly.
Resolves [google-cloud-node#1875](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1875).
=> Fix 'progress' event.

lib/longrunning.js, package.json, test/api_callable.js
It appears that `Buffer.from("")` does not work for node versions `>4.0.x` but `<4.5.x` and does not work for node versions `>5.0.x` and `<5.10.x`. This fix removes the use of Buffer.from in the implementation.
This also adds additional logic to checking if there is an update to the metadata.
=> Buffer.from fix and logic fix.

lib/streaming.js, test/api_callable.js
- server-streaming: 3 arguments (request, metadata, options).
The callback must not exist.
- client-streaming: 3 arguments (metadata, options, callback).
The request must not exist.
- bidi-streaming: 2 arguments (metadata, options).
Both request and callback must not exist.
Also added test cases.
=> Fix server-streaming request pattern.

lib/longrunning.js, test/api_callable.js
=> LRO: getOperation should return a promise when callback is not specified.

lib/api_callable.js, lib/gax.js, lib/grpc.js, lib/longrunning.js, test/api_callable.js, test/longrunning.js
The PR allows for gapic-clients to be able to be passed a module that fulfills the ES6 specification of promises and use that module for creating promises.
Example: Specify promise at instantiation.
```js
var exampleV1 = require('@google-cloud/example').v1({
promise: require('bluebird')
});
// Any client created from exampleV1 will be using bluebird now.
var client = exampleV1.libraryClient();
```
Example: Specify promise at method invokation.
```js
var exampleV1 = require('@google-cloud/example').v1({});
var client = exampleV1.libraryClient();
client.getBook(name, {
promise: require('bluebird')
}).then(function(responses) {
...
});
```
=> Allow type of promise used to be varying.

package.json
Due to the grpc releases of 1.1.x.
See also:
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1946
=> Update grpc dependency version to ~1.1

lib/api_callable.js, lib/grpc.js, package.json, test/api_callable.js, test/grpc.js
This PR allows the A/B testing values for X-Goog-Api-Client header.
Also grpcVersion field is added -- this is going to be used
by the generated code to build the base header value.
=> Modify the handling of the new API header.

lib/grpc.js, lib/operations_client.js, lib/operations_client_config.json, package.json, test/grpc.js
With toolkit changes, this allows customizing grpc behaviors.
See:
- https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1991
- https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1905
updates #107
=> Pass through options to grpc client creation.

package.json
0.12.1 was wrongly published with the same content with
0.12.0 -- the new fix comes with 0.12.2.
=> Update the version.

lib/grpc.js, test/grpc.js
=> Allow grpc custom channel without auth.

lib/api_callable.js, test/api_callable.js
cc @stephenplusplus 
This should help users set other headers as needed [here](https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2195#discussion_r110702349)
=> Allow users to pass in headers at method call.

package.json
This is to include #129, #130 to help with [google-cloud-node/pull/2195](https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2195)
=> Version bump for 13.1 release

lib/grpc.js
Without this fix, I am getting unhandled rejections with the `@google-cloud/logging`.
```
❯ node --trace-warnings index.js
[ 0, 4282461 ]
undefined
(node:44617) TypeError: Cannot read property 'config' of undefined
at Auth.getAuthClient (/Users/ofrobots/tmp/log-t/node_modules/google-gax/node_modules/google-auto-auth/index.js:38:20)
at /Users/ofrobots/tmp/log-t/node_modules/google-gax/lib/grpc.js:90:5
at GrpcClient._getCredentials (/Users/ofrobots/tmp/log-t/node_modules/google-gax/lib/grpc.js:89:10)
at GrpcClient.createStub (/Users/ofrobots/tmp/log-t/node_modules/google-gax/lib/grpc.js:172:15)
at new LoggingServiceV2Client (/Users/ofrobots/tmp/log-t/node_modules/@google-cloud/logging/src/v2/logging_service_v2_client.js:122:38)
at Object.LoggingServiceV2ClientBuilder.loggingServiceV2Client …
```
=> getAuthClient is an instance method

lib/api_callable.js, test/api_callable.js
Fixes #136
I've double-checked the behavior of gax-python, and it has
the check like
`if this_settings.retry and this_settings.retry.retry_codes`
Similar code exists here, but JavaScript empty array [] is
truthy, so it passes to the retryable code path. It should check
if the code length explicitly to be consistent with other
languages.
=> Use 'timeout' for non-idempotent API calls.

lib/longrunning.js, package.json, test/longrunning.js
Florence reported a bug in Node where the LRO times out with a sufficiently large video.
After investigating, it turns out that this is because we have a hard-coded 10 minute total timeout. This is reasonable for most languages where this is a poll in the background that you can easily restart, but in Node, the operation provides `op.promise()` which is a one-and-done. Once the Promise is rejected, that is it. This makes even a very long timeout problematic.
While eventually we need to approach these settings differently as a whole, for the moment, this PR simply makes the timeout be `null` so that we can unblock video intelligence.
Assigned to @geigerj or @swcloud for review. Once either of you has approved, please feel free to merge and push to npm.
=> Kill LRO total timeout.

lib/api_callable.js, lib/grpc.js, test/api_callable.js, test/grpc.js
Instead of creating fresh metadata every time,
we keep a copy-on-write instance.
In the hopefully-common case that the users don't need
to insert any metadata, we don't need to create new ones.
This commit also fixes a bug related to x-goog-api-client header.
Previously we checked the key string against "x-goog-api-client"
and refuse to insert the value if the key matches.
This is incorrect because header key is case-insensitive;
by making any character upper case, the key-value pair can be overwritten.
This commit correctly compares ignoring case.
=> make metadata faster

package.json
This change picks up fixes introduced in v0.7.1 of `google-auto-auth`, notably related to context loss.
=> deps: bump google-auto-auth dependency

package.json
https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2784
https://github.com/grpc/grpc-node/issues/130
https://github.com/googleapis/nodejs-datastore/issues/35
=> Downgrade gRPC to ~1.7

package.json
Firestore appears to have authentication issues after switching to grpc 1.8, so rolling back.
=> fix: downgrade grpc back to 1.7.2, bump version to 0.14.5

lib/streaming.js, package.json, test/streaming.js
I ran into an issue where I wasn't able to apply flow control to a stream because the StreamProxy class wouldn't wait for the underlying stream to finish writing data.
Once I looked closer at the StreamProxy class I noticed we could simplify it by leveraging Duplexify.
=> refactor: use duplexify within StreamProxy

package-lock.json, package.json
This release has several dependencies updates, most importantly, `grpc` is upgraded to version 1.10.0.
=> chore: prepare 0.16.1 release

src/grpc.ts, src/operations_client.ts, test/grpc.ts
BREAKING CHANGE: removing `GrpcClient.load()` which was a wrapper for `grpc.load`. In `GrpcClient.loadProto()` replacing `grpc.loadObject` with a (hopefully compatible) call to `@grpc/proto-loader`.
I'm going to test this in several client libraries and see if anything breaks (which is highly possible).
Fixes #286.
=> feat: use @grpc/proto-loader instead of deprecated grpc load

src/grpc.ts, src/index.ts
We have a situation in some npm modules where we are importing multiple versions of google-auth-libraries.  This can cause all sorts of weird problems, and I'd like high level modules to get their auth from here or common.
=> Export GoogleAuth for consumption

src/grpc.ts, src/operations_client.ts
Fixes #286 (again).
We don't use `grpc.load` but still need to use `grpc.loadObject`. I'm not sure yet how we need to redesign it, but since `loadObject` is not deprecated, let's just try that.
I'll release a new version after this one is merged, and we'll see if it works :)  (I checked manually on some libraries though)
=> fix: reverting to use grpc.loadObject for now

package.json, src/grpc.ts
This should trim ~120ms from our module load time.  Please take a close look at this one, because it could break a lot 😆
=> fix: use `walkdir` instead of `globby`

system-test/system.ts
Pub/Sub compilation is broken and will be fixed in the next release (> v0.21.1). Disabling until then.
=> test: don't run Pub/Sub system tests

src/operations_client.ts
Fixes #54 (kind of fixes, since #54 asks to stop editing auto-generated file and I suggest that this file should not be auto-generated anymore).
=> chore: don't say operations_client.ts is autogen'd

system-test/system.ts
Now that the Pub/Sub problem is fixed in v0.22.0, let's re-enable it in system tests.
=> test: enable pub/sub system tests

.circleci/config.yml
Looks like gax is still affected by this openssl defaults change.
=> chore: fix openssl decrypt

src/gax.ts
Fixes misleading documentation
=> docs: fix type for retryCodes

package.json
@kinwa91 will enable system tests with grpc-js as a separate Kokoro task.
It's a little bit flaky now so will likely bring more harm than good.
But good news is that it works (#400)!
=> chore: don't run system tests with grpc-js

package.json
This was originally merged in #417 but looks like it got lost in merges. We still need to remove this since we now have a separate Kokoro task for grpc-js.
=> test: do not use grpc-js in regular system test

src/bundling.ts, src/isbrowser.ts, src/streaming.ts, src/warnings.ts, test/warning.ts, tsconfig.json
Make it easy to warn. Inspired by https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/messages.ts but since we don't warn much in this library, decided to make it easier (YAGNI).
=> fix: do not use console.warn or console.error

src/bundling.ts, test/bundling.ts
Workaround for https://github.com/googleapis/nodejs-logging/issues/381. In some weird cases we can get `undefined` where we expect an array of values to be bundled in one call. It should not happen, but if it does, let's not fail there.
Fail happens here:
https://github.com/googleapis/gax-nodejs/blob/218232f8fc2ef5d1200e5c8cbc4d1709bd7c6f85/src/bundling.ts#L381-L382
=> fix: do not fail if bundledField is missing

src/grpc.ts
Makes https://github.com/googleapis/nodejs-irm/pull/8 work since this nodejs-irm library depends on monitoring protos which were never listed as common protos.
=> fix: monitoring could be a common proto

src/longrunning.ts, test/longrunning.ts
Speech API `LongRunningRecognize` can return no result and no error in case if the input file has no speech in it. This should be fixed on the server side but it makes sense to stop waiting in LRO if there is nothing to wait for.
=> fix: do not hang in LRO forever if API returned nothing

package.json
This library uses `duplexify`, and returns objects that use types from the `@types/duplexify` package in public interfaces.  This is causing issues like the one seen here:
https://github.com/googleapis/nodejs-datastore/pull/346
=> fix: includes @types/duplexify in package

src/gax.ts
Adapding gax for TypeScript micro-generator (which is coming like really soon).
=> fix: bundling is optional in MethodConfig

test/utils.ts
Fixes the failing build that fails after #461.
=> test: better return type for typescript 3.4.0

package.json, system-test/fixtures/google-gax-packaging-test-app/package.json
gRPC v1.20.2 is out fixing the typing problems in v1.20.1, so unpinning it back.
=> chore(dep): unpin grpc

src/grpc.ts
Finally, `loadPackageDefinition` just works for both grpc versions we have.
=> feat: do not use legacy grpc loadObject

Operation/index.html
Fixes broken links to `Operation` (e.g. here https://github.com/googleapis/nodejs-spanner/pull/610).
=> add one more redirect to gh-pages

src/grpc.ts, test/grpc.ts
This will allow us to stop using `lodash.merge` in cases like [this one](https://github.com/googleapis/nodejs-pubsub/blob/c72491f9c3e68fff5d05f13ae73ea7e75b90c18b/src/v1/subscriber_client.js#L93-L103). It [turns out](https://github.com/grpc/grpc-node/issues/805) merging protos is supported by Protobuf.js and (unofficially, [proposal pending](https://github.com/grpc/proposal/pull/143)) supported by `@grpc/proto-loader`, so let's just use it and then remove `lodash.merge` from the client libraries.
This is a compatible, non-breaking, change. GAX v1.1.0 is coming!
=> feat: allow loading multiple proto files at once

CHANGELOG.md, package.json, samples/package.json
This is a step to remove `lodash.merge` from our client libraries.
=> chore: release 1.1.0

package.json, src/grpc.ts
The new patch release of `@grpc/proto-loader` updates types for `load` and `loadSync` so we don't need that `any` anymore.
=> fix: use latest proto-loader with fixed types

src/bundlingCalls/bundleExecutor.ts, src/bundlingCalls/task.ts, src/call.ts, src/longRunningCalls/longrunning.ts, src/normalCalls/retries.ts, src/status.ts
We use this `Status` enum here and there, and when we create a webpack bundle, it tries to bundle all the `@grpc/grpc-js` even if all it needs it just this tiny enum.
Let's just make a copy of it - maybe not the cleanest, but the easiest solution.
=> refactor: do not use Status from grpc-js

src/routingHeader.ts, test/routingHeader.ts
Fixes #520 (cc: @schmidt-sebastian)
Turns out we had our very own implementation of `querystring.stringify`. Not anymore.
=> fix: routing header parameters must be urlencoded

src/browser.ts
Because gRPC-fallback doesn't support streaming calls, I added a check on streaming calls to throw an exception when the user attempts to call any streaming functions.
=> throw exception on streaming calls

src/longRunningCalls/longrunning.ts, test/longrunning.ts
Fixes https://github.com/googleapis/nodejs-speech/issues/397.
Seems like some properties of the `Operation` wrapper were never set. Fixing it.
=> fix: copy values from LRO to Operation wrapper

package.json
This fix includes https://github.com/grpc/grpc-node/pull/962 which is a work around for a bad metadata keys problem that many customer see across several libraries (https://github.com/googleapis/nodejs-datastore/issues/415, https://github.com/googleapis/nodejs-logging/issues/527, https://github.com/googleapis/nodejs-pubsub/issues/667 are just a few).
Fixes https://github.com/googleapis/nodejs-datastore/issues/415
Fixes https://github.com/googleapis/nodejs-logging/issues/527
=> chore(deps): update dependency @grpc/grpc-js to ^0.5.2

README.md
To make `linkinator` work better (that is, ignore the codecov.io URLs in its checks).
=> docs: fix the url for codecov.io

src/grpc.ts, test/grpc.ts
This fix allows to call `gaxGrpc.loadProto(file)` passing just one file as a parameter. The current API only allows two parameters (folder and filename). This change is compatible and allows for simpler `loadProto` usage for the use case when just one proto file must be loaded.
(and it will be used in client libraries soon!)
=> feat: allow to pass just one file path to loadProto

src/index.ts, test/grpc.ts
We sometimes need `protobufjs` in client libraries (e.g. for LRO proto loading). gapic-generator does not do a great job detecting if `protobufjs` is needed or not for the given client library, which sometimes causes lint errors about unused dependency.
Since `protobufjs` is an important part of gax, it will always be installed within gax. Let's just reexport it from gax, so that the client library used `gax.protobuf.loadSync`, `gax.protobuf.Root`, etc. whenever needed. By doing this, we'll remove `protobufjs` dependency from the client libraries, and also will make sure there will be no compatibility problems between two `protobufjs` dependencies.
=> feat: reexport protobufjs from gax

test/compileProtos.ts, test/fixtures/protoLists/empty/README.txt, tools/compileProtos.ts
OK so I wrote this `compileProtos` script and it works, now let's fix some corner cases :)
This one makes it not fail if no protos are there yet (which will simplify our transition it a lot). Basically, no protos => no JSON (empty object).
Also, `compileProtos` needs to have use common protos (that are a part of `google-gax` distribution). To make it easier to run the script from a library folder without doing an extra `npm install`, let's use `__dirname` as a starting point for looking up those common protos.
=> fix: compileProtos should not fail if no protos are given

browser-test/test.grpc-fallback.ts, src/browser.ts
Changed constructSettings() and createStub() to support sending extra headers (set in options) through fallback requests.
=> feat: support sending `x-goog-request-params` (and other extra) headers for fallback requests 

package.json, src/browser.ts, test/grpc-fallback.ts
This PR adds abort functionality for Node.js gRPC-fallback scenario (using the same `AbortController` logic as in browser scenario), and also adds some unit test for Node.js fallback.
It will wait for #568 and then I'll merge it in.
=> feat: add AbortController for node-fetch

src/fallback.ts, test/unit/exports.ts
Specifying gax external interface and verifying it in a unit test. Also, exporting `version` from `fallback`.
Note: nobody uses `fallback` now, so I can consider adding one export to it as a bug fix, not a minor release. We need the version to be exported to make sure the header sent by client library working in a fallback mode is not blank.
=> fix: export version from fallback

package.json, protos/status.json, src/fallback.ts, src/fallbackError.ts, test/browser-test/test.grpc-fallback.ts, test/fixtures/error.bin, test/unit/fallbackError.ts, test/unit/grpc-fallback.ts, webpack.config.js
We did not handle errors (4xx HTTP codes) in gRPC-fallback code properly.
According to the [document](https://googleapis.github.io/HowToRPC#grpc-fallback-experimental), in case of an error, the HTTP response payload is a serialized instance of `google.rpc.Status`.
=> fix: properly handle gRPC-fallback errors

src/fallback.ts, test/unit/exports.ts
This PR make the exported `version` (that goes to the `gax/` field of `x-goog-api-client`) say if it's a fallback or regular version of gax. This makes sense, since even though they share versions, the fallback one uses totally different code.
=> fix: make fallback version unique

package.json, test/system-test/showcase-server.ts
`tar` npm package suddenly stopped working in Kokoro (it still works locally though). I don't think we need to investigate it, let's just use `tar` binary directly. It's only in the test code, to unpack the Showcase server.
=> test: use tar directly in tests

src/operationsClient.ts
We don't really need to force users to pass `clientConfig` in the options, `undefined` works just fine.
=> fix: clientConfig can be omitted

src/longRunningCalls/longrunning.ts
This code was added during an internship project, was reviewed by several folks and got into master but it's a little bit wrong (accesss an element at `a.length`).
Fixing the comparison to remove the off by one error. We still cannot use `Buffer` because this code is supposed to work in browser as well.
@noahdietz just FYI, we missed an off by one :)
=> fix: correct array comparison

test/system-test/test.clientlibs.ts
One test in the Pub/Sub system tests keeps failing under our service account. While this is being investigated (@callmehiphop FYI), I'll just disable this one test from google-gax system tests with a small hack. Calling `perl -p -i -e` with a regex from Node.js system test, what can go wrong here.
=> test: skip the failing pubsub test

test/unit/compileProtos.ts, tools/compileProtos.ts
The protobuf.js PR https://github.com/protobufjs/protobuf.js/pull/1166 was merged ages ago but still not released. I suspect it might take some more time to release it, so - since this script is the one place to generate proto TS file - let's do it from here for now.
It will only add a missing import if it's not there already, so when the the protobuf.js PR is finally released, it won't break and we'll just remove it from here.
=> fix: add long to protos.d.ts

package.json
As suggested in https://github.com/googleapis/gapic-generator-typescript/pull/118, let's just have this dependency here and not in every client library.
=> fix: depend on @types/long

src/index.ts
Unblocks https://github.com/googleapis/gapic-generator-typescript/pull/126
=> feat: export APICallback type

package.json
Fixes #642 by reverting TypeScript dependency back to `~3.6.0`.
=> fix(deps): use typescript ~3.6.0

package.json
Unpinning `@grpc/grpc-js`. Will be released as 1.11.2.
=> fix(deps): unpin @grpc/grpc-js, set it to ^0.6.12

test/system-test/test.clientlibs.ts
Let's remove pubsub tests from gax system tests for now since they started failing. I filed https://github.com/googleapis/nodejs-pubsub/issues/826 and will put them back when they work again.
=> test: skip pubsub system tests

src/fallback.ts, src/grpc.ts
Fixes https://github.com/googleapis/nodejs-text-to-speech/issues/298. I'm not sure why `servicePath` and `port` were set as required, because they are not.
=> fix: servicePath and port may be undefined

package.json
Use `c8` for coverage in `google-gax`.
=> chore: use c8 for coverage

src/index.ts
Seems like we need to properly export `OperationsClient` from TypeScript libraries to give users access to low level LRO stuff. https://github.com/googleapis/nodejs-speech/issues/483
Let's first export it from gax, then I'll update the generator.
=> feat: export OperationsClient

src/index.ts, test/system-test/test.clientlibs.ts
This should allow me to use the same status codes in Firestore. Right now, we have our own copy (https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/watch.ts#L62). FWIW, this enum is used in the exported GoogleError.
=> feat: export GRPC error code enum

src/index.ts
I would also like to export ServiceConfig, so I don't have to pass the full ClientConfig to my utility methods
=> feat: export ServiceConfig

test/browser-test/test.grpc-fallback.ts, test/system-test/showcase-server.ts, webpack.config.js
#692 broke karma+mocha magic, here is the fix.
(also, no idea why we have `it.only` in browser tests, it's not supposed to be there, so removing it)
=> test: fix browser tests

.kokoro/continuous/node12/browser-test.cfg, .kokoro/presubmit/node12/browser-test.cfg
Run browser tests on Node 12 since 8 got broken too quick.
Browser tests in this PR might still fail until some other settings are in place and Docker image is ready.
=> chore: run browser testing on node 12

.gitignore, test/fixtures/dts-update/google/dts.proto, test/fixtures/dts-update/test_proto_list.json, test/unit/compileProtos.ts, tools/compileProtos.ts
Fixes https://github.com/googleapis/gapic-generator-typescript/issues/196, https://github.com/googleapis/nodejs-tasks/issues/334, https://github.com/googleapis/nodejs-iot/issues/250, https://github.com/googleapis/nodejs-scheduler/issues/181, https://github.com/googleapis/nodejs-tasks/issues/331 (and maybe more).
We will accept enum string values in TypeScript request and response types, just like our JavaScript samples suggest to do.
In this PR I'm updating the `compileProtos` tool so that the request and response types accepted strings for enums, `bytes`, and `Long`. For enums, I'm using the magic [`keyof typeof`](https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-compile-time) TypeScript feature to only allow _proper_ strings as values. For `bytes`, `protobuf.js` allows …
=> feat: allow strings for enums, bytes, and Long in .d.ts

test/fixtures/dts-update/google/dts.proto, test/unit/compileProtos.ts, tools/compileProtos.ts
The yesterday's fix #714 works perfectly with one exception: if a proto message has a field that is a reserved word in TypeScript, it does not detect it.
Example (real-life from Language API):
```proto
message PartOfSpeech {
...
enum Case {
...
}
...
Case case = 3;
...
}
```
```ts
interface IPartOfSpeech {
...
"case"?: (google.cloud.language.v1.PartOfSpeech.Case|null);
...
}
// note that in class it's totally fine because of the "public" keyword:
class PartOfSpeech implements IPartOfSpeech {
...
public case: (google.cloud.language.v1.PartOfSpeech.Case|keyof typeof google.cloud.language.v1.PartOfSpeech.Case);
...
}
```
This fix allows for quotes around the field name in the `.d.ts` interface definitions. Checked that it fixes the above problem. Added a test for this scenario.
=> fix: properly parse special field names in compileProtos

package.json
PR for https://github.com/googleapis/gax-nodejs/issues/727
=> deps: update grpc-js minimum version to 0.6.18 to catch the recent retry fixes

package.json
The new `protobufjs` v6.8.9 has some old dependencies updated.
=> fix(deps): use protobuf.js v6.8.9

.github/workflows/ci.yaml, src/grpc.ts
This is waiting on landing: https://github.com/googleapis/google-cloud-node/pull/2980
_Note: we should test this in cloud functions once we get the first library using this version._
=> feat!: throw for versions of Node.js older than v10.0.0

src/index.ts
This is coming up during the TypeScript transition in Bigtable.  This type appears to be used everywhere.
=> feat: export ServiceError from @grpc/grpc-js

src/pathTemplate.ts, test/unit/pathTemplate.ts
Fixes the problem shown in https://github.com/googleapis/nodejs-dialogflow/pull/568 - it makes no harm if we just allow passing numbers as path template parameters, and silently convert them to strings under the hood.
=> fix: allow passing numbers as path template parameters

samples/package.json, samples/pagination.js, src/apitypes.ts, src/paginationCalls/pageDescriptor.ts, test/fixtures/google-gax-packaging-test-app/src/index.js, test/fixtures/google-gax-packaging-test-app/src/v1beta1/echo_client.js, test/unit/pagedIteration.ts
**TL;DR:** this is a small refactor of the client functionality that was not released yet. Pretty safe to merge since async iteration in clients is not enabled yet.
---
So this turned to be a refactor that made the async iteration code a little bit simpler.
Background: it turns out async iteration, as implemented, did not work for gRPC-fallback clients. The main reason for that is that `createApiCall` is implemented differently in `fallback.ts`, and fallback clients expect that exact implementation. Long story short, it was not possible to call a stub of `pagedExpand` in `pagedExpandAsync`; fallback clients needed the result of `createApiCall`.
So... since the result of `createApiCall` is a function and not a promise, we can remove all the complicated asynchronous stuff (uninitialized …
=> fix: make async iteration work for gRPC-fallback; refactor the code

samples/system-test/test.pagination.js, samples/system-test/test.quickstart.js, test/fixtures/package.json, test/system-test/showcase-server.ts, test/unit/compileProtos.ts, tools/compileProtos.ts
If we look into the generated `protos/protos.js`, we'll see this:
```js
(function(global, factory) {
...
})(this, function($protobuf) {
...
var $root = $protobuf.roots["default"] || ($protobuf.roots["default"] = {});
...
});
```
This breaks loaded protos if more than one library is loaded within one process, and exactly this happens in container analysis (+grafeas). So let's pass `-r` option to `pbjs` so that the above line becomes more unique:
```js
var $root = $protobuf.roots._google_cloud_containeranalysis_1_10_0_protos ||
($protobuf.roots._google_cloud_containeranalysis_1_10_0_protos = {});
```
There are currently no user-visible changes, so I consider this a non-breaking fix. I checked locally that it helps containeranalysis unit tests :)
(this was uncovered by improving the …
=> fix: make sure generated protos.js have unique root name

src/grpc.ts, src/index.ts
I need this for a fix I want to make in datastore
=> fix(types): use grpc call credentials type

test/system-test/test.clientlibs.ts
KMS api is migrated to use IAM service from gax, it's time to include this API as a system-test to cover ability of calling IAM methods.
=> feat: add IAM system-test

package.json, src/grpc.ts, test/unit/compileProtos.ts, test/unit/grpc.ts
Let's start using `@grpc/grpc-js` v1.0.0.
Since starting from v0.8.x `@grpc/grpc-js` enforces `grpc.max_receive_message_length`, we need to pass an extra gRPC option to disable it. Apparently we had a bug in the option code that stripped `grpc.` from the option names, so the client actually needed to pass `grpc.grpc.*` instead of `grpc.*` :)  Removing this now would be a breaking change, so I'll have a temporary fix in place until the time when we go to 3.0.0, just in case.
=> fix: use @grpc/grpc-js v1.0.0, pass grpc options properly

src/longRunningCalls/longrunning.ts, src/operationsClient.ts, test/unit/longrunning.ts, test/unit/operationClient.ts
`longrunning.ts` needs a `getOperation` method which returns a cancellable promise, while external users call `getOperation` method to get a response as a longrunning `Operation`. So we decide to separate the call, one is `getOperationInternal` for longrunning, it returns `CancellablePromise<ResultTuple>`. And the other one is for external users which returns `Operation` type.
related change: https://github.com/googleapis/gapic-generator-typescript/pull/420
=> fix: add an internal getOperation method in operation client

src/grpc.ts, test/unit/grpc.ts
gRPC options are weird. Regular gRPC options are prefixed `grpc.` and should be passed down as `grpc.*`, while the three known `grpc-gcp` options should be passed without a prefix.
This partially rolls back my refactor in #809 to make `grpc-gcp` work.
=> fix: strip grpc. prefix for grpc-gcp options

src/operationsClient.ts, test/unit/operationClient.ts
related: https://github.com/googleapis/gapic-generator-typescript/pull/420
=> fix: return operation array from getOperation method

src/grpc.ts, test/unit/grpc.ts
This finally fixes the options processing problem I introduced in #809 and only partially fixed in #814. 
Basically, when you change the key, don't expect that you will still be able to find a value.
Also, if your unit tests only check for keys, don't expect they will catch this bug.
Lessons learned :)
=> fix: do not pass undefined as option values

test/unit/grpc.ts, test/unit/pagedIteration.ts
Seems like with TypeScript 3.9 it became even more strict. Fixing the build.
=> fix: new typescript, strict types

test/browser-test/test.grpc-fallback.ts, test/unit/grpc-fallback.ts
This is the first known case where the compilation is fixed by _removing_ `any` and not by _adding_ one. TypeScript is becoming perfect in handling types :)
=> fix: typescript 3.9.3 compilation

src/pathTemplate.ts, test/unit/pathTemplate.ts
we allow non-slash resource now, for example:
```
user/{user_id}/blurbs/legacy/{blurb_id}.{legacy_user}'
```
=> feat: support non-slash resource in path template

src/pathTemplate.ts, test/unit/pagedIteration.ts, test/unit/pathTemplate.ts
failing case: match `projects/{project=*}` with `project: long-project-name` from dialogflow sample-test
https://github.com/googleapis/nodejs-dialogflow/pull/617
the original logic is to check the matching string (`long-project-name`) if it can be divided by `-_.~`, to decide whether it's non-slash resource (for example match `{user_a}-{user_b}` with `usera-userb`). but it will fail for the above case.
Now we check the segments `{project=*}` if it has multiple brackets, it will be taken as non-slash resource (for example `{user_a}-{user_b}`
=> fix: fix match logic for path template

package.json
In this PR, I'm just making sure we use v2.1.0+ of `google-proto-files`. It will pull the latest `google/protobuf/compiler/plugin.proto` that has support for a new plugin feature (`optional` syntax for `proto3`).
=> feat: support proto3 optional fields in exported protos

test/fixtures/package.json, test/unit/compileProtos.ts, tools/compileProtos.ts
Having the package version there is too much since it updates every time we bump a version. Just the package name is enough.
=> fix: remove version from protobuf unique root name

src/gax.ts
=> chore: document the way to override bundling options

src/pathTemplate.ts, test/system-test/test.clientlibs.ts, test/unit/pathTemplate.ts
[monitoring](https://github.com/googleapis/nodejs-monitoring/pull/436) now fails for this.
=> fix: segment in path template can contain wildcard

package.json, test/fixtures/google-gax-packaging-test-app/package.json
This PR bumps the minor version of `@grpc/grpc-js` to 1.1.x.
Cc: @murgatroid99
=> fix(deps): use @grpc/grpc-js ~1.1.1
